/** Generates src/generated/* from schema/v0/aggregates.schema.json. Run via `make gen`. */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const root = fileURLToPath(new URL("..", import.meta.url));
const schemaPath = `${root}schema/v0/aggregates.schema.json`;
const outDir = `${root}src/generated/`;
const header = "/* Generated by `make gen` from schema/v0/aggregates.schema.json. Do not edit. */\n";

const schema = JSON.parse(await readFile(schemaPath, "utf8")) as Record<string, unknown>;
await mkdir(outDir, { recursive: true });

const types = await compile(schema as Parameters<typeof compile>[0], "AggregatesBatch", {
  bannerComment: header.trimEnd(),
  additionalProperties: false,
  style: { semi: true, singleQuote: false, printWidth: 120 },
});
await writeFile(`${outDir}aggregates.ts`, types);

const accepted = (schema.properties as Record<string, { enum?: unknown }>).protocol?.enum;
if (!Array.isArray(accepted) || accepted.length === 0) throw new Error("schema: properties.protocol.enum missing");
const current = accepted[accepted.length - 1];
await writeFile(
  `${outDir}versions.ts`,
  `${header}
/** Every published minor of v0, oldest first. The cloud never stops accepting one it published (ADR 0008). */
export const ACCEPTED_PROTOCOL_VERSIONS_V0 = [${accepted.map((v) => JSON.stringify(v)).join(", ")}] as const;

/** The newest published minor: what an up-to-date agent stamps on every batch. */
export const PROTOCOL_VERSION = ${JSON.stringify(current)};
`,
);

const defs = schema.$defs as Record<string, Record<string, unknown>>;
const boundaries = defs.LatencyHistogram?.["x-latency-boundaries-ms"] as number[];
if (!Array.isArray(boundaries)) throw new Error("schema: LatencyHistogram.x-latency-boundaries-ms missing");
const queryBoundaries = defs.Dependency?.["x-calls-per-request-boundaries"] as number[];
if (!Array.isArray(queryBoundaries)) throw new Error("schema: Dependency.x-calls-per-request-boundaries missing");
await writeFile(
  `${outDir}boundaries.ts`,
  `${header}
/** Upper bounds (ms) of the fixed latency buckets; the last bucket is open-ended. */
export const LATENCY_BOUNDARIES_V0: readonly number[] = [${boundaries.join(", ")}];

/** Number of buckets: boundaries + 1 open-ended bucket. */
export const LATENCY_BUCKETS_V0 = ${boundaries.length + 1};

/** Upper bounds of the fixed calls-per-request buckets; the last bucket is open-ended. */
export const CALLS_PER_REQUEST_BOUNDARIES_V0: readonly number[] = [${queryBoundaries.join(", ")}];

/** Number of calls-per-request buckets: boundaries + 1 open-ended bucket. */
export const CALLS_PER_REQUEST_BUCKETS_V0 = ${queryBoundaries.length + 1};
`,
);
console.log(
  `generated aggregates.ts, versions.ts (protocol ${current}) and boundaries.ts (${boundaries.length + 1} buckets)`,
);
