/** Generates src/generated/* from schema/v0/aggregates.schema.json. Run via `make gen`. */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const root = fileURLToPath(new URL("..", import.meta.url));
const schemaPath = `${root}schema/v0/aggregates.schema.json`;
const outDir = `${root}src/generated/`;
const header = "/* Generated by `make gen` from schema/v0/aggregates.schema.json. Do not edit. */\n";

const schema = JSON.parse(await readFile(schemaPath, "utf8")) as Record<string, unknown>;
await mkdir(outDir, { recursive: true });

const types = await compile(schema as Parameters<typeof compile>[0], "AggregatesBatch", {
  bannerComment: header.trimEnd(),
  additionalProperties: false,
  style: { semi: true, singleQuote: false, printWidth: 120 },
});
await writeFile(`${outDir}aggregates.ts`, types);

const defs = schema.$defs as Record<string, Record<string, unknown>>;
const boundaries = defs.LatencyHistogram?.["x-latency-boundaries-ms"] as number[];
if (!Array.isArray(boundaries)) throw new Error("schema: LatencyHistogram.x-latency-boundaries-ms missing");
await writeFile(
  `${outDir}boundaries.ts`,
  `${header}
/** Upper bounds (ms) of the fixed latency buckets; the last bucket is open-ended. */
export const LATENCY_BOUNDARIES_V0: readonly number[] = [${boundaries.join(", ")}];

/** Number of buckets: boundaries + 1 open-ended bucket. */
export const LATENCY_BUCKETS_V0 = ${boundaries.length + 1};
`,
);
console.log(`generated aggregates.ts and boundaries.ts (${boundaries.length + 1} buckets)`);
